@echo off
setlocal enabledelayedexpansion
title AcadTrack Setup

:: ═══════════════════════════════════════════════════════════════
::  AcadTrack — One-Click Setup Script
::  Run this ONCE after cloning the repository on a new device.
::  Requirements: Node.js 18+, XAMPP (Apache + MySQL running)
:: ═══════════════════════════════════════════════════════════════

echo.
echo  ╔══════════════════════════════════════════╗
echo  ║        AcadTrack  Setup Wizard           ║
echo  ║    University Management System          ║
echo  ╚══════════════════════════════════════════╝
echo.

:: ─── Step 0: Check we are in the right folder ───────────────────
if not exist "package.json" (
    echo  [ERROR] package.json not found.
    echo  Please run this script from the root of the AcadTrack project folder.
    pause & exit /b 1
)

:: ─── Step 1: Check Node.js ───────────────────────────────────────
echo  [1/7] Checking Node.js...
node --version >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo  [ERROR] Node.js is not installed or not in PATH.
    echo  Download it from: https://nodejs.org  ^(LTS recommended^)
    echo.
    pause & exit /b 1
)
for /f "tokens=*" %%v in ('node --version') do set NODE_VER=%%v
echo         Found Node.js %NODE_VER%  OK

:: ─── Step 2: Find MySQL (XAMPP) ──────────────────────────────────
echo  [2/7] Locating MySQL (XAMPP)...

set MYSQL_EXE=
for %%P in (
    "C:\xampp\mysql\bin\mysql.exe"
    "D:\xampp\mysql\bin\mysql.exe"
    "C:\xampp2\mysql\bin\mysql.exe"
) do (
    if exist %%P set MYSQL_EXE=%%~P
)

:: Also check PATH
if "%MYSQL_EXE%"=="" (
    where mysql >nul 2>&1
    if %errorlevel% equ 0 (
        for /f "tokens=*" %%m in ('where mysql') do (
            if "!MYSQL_EXE!"=="" set MYSQL_EXE=%%m
        )
    )
)

if "%MYSQL_EXE%"=="" (
    echo.
    echo  [ERROR] MySQL executable not found in common XAMPP paths or PATH.
    set /p MYSQL_EXE="  Enter full path to mysql.exe: "
    if not exist "!MYSQL_EXE!" (
        echo  [ERROR] Path does not exist: !MYSQL_EXE!
        pause & exit /b 1
    )
)
echo         Found MySQL at: %MYSQL_EXE%  OK

:: ─── Step 3: Collect configuration ──────────────────────────────
echo.
echo  [3/7] Configuration
echo         Press ENTER to accept the [default] value shown in brackets.
echo.

set /p DB_HOST="  DB Host       [localhost]: "
if "%DB_HOST%"=="" set DB_HOST=localhost

set /p DB_PORT="  DB Port       [3306]: "
if "%DB_PORT%"=="" set DB_PORT=3306

set /p DB_NAME="  DB Name       [acadtrack]: "
if "%DB_NAME%"=="" set DB_NAME=acadtrack

set /p DB_USER="  DB User       [root]: "
if "%DB_USER%"=="" set DB_USER=root

set /p DB_PASS="  DB Password   [leave blank for XAMPP default]: "

set /p APP_URL="  App URL       [http://localhost:3000]: "
if "%APP_URL%"=="" set APP_URL=http://localhost:3000

set /p BREVO_KEY="  Brevo API Key [leave blank to skip email]: "

:: Generate a random JWT secret using PowerShell
echo.
echo         Generating JWT secret...
for /f "tokens=*" %%g in ('powershell -Command "[System.Guid]::NewGuid().ToString('N') + [System.Guid]::NewGuid().ToString('N')"') do set JWT_SECRET=%%g
echo         JWT secret generated.

:: ─── Step 4: Write .env.local ────────────────────────────────────
echo.
echo  [4/7] Writing .env.local...

(
echo # Auto-generated by setup.bat — do NOT commit this file
echo DB_HOST=%DB_HOST%
echo DB_PORT=%DB_PORT%
echo DB_NAME=%DB_NAME%
echo DB_USER=%DB_USER%
echo DB_PASS=%DB_PASS%
echo JWT_SECRET=%JWT_SECRET%
echo JWT_EXPIRES_IN=7d
echo COOKIE_NAME=acadtrack_token
echo NEXT_PUBLIC_APP_URL=%APP_URL%
echo BREVO_API_KEY=%BREVO_KEY%
echo MAIL_FROM_NAME=AcadTrack
echo MAIL_FROM=noreply@acadtrack.com
) > .env.local

echo         .env.local created  OK

:: ─── Step 5: npm install ─────────────────────────────────────────
echo.
echo  [5/7] Installing npm packages (this may take a minute)...
echo.
call npm install
if %errorlevel% neq 0 (
    echo.
    echo  [ERROR] npm install failed. Check the output above.
    pause & exit /b 1
)
echo.
echo         npm install complete  OK

:: ─── Step 6: Create database and run SQL files ───────────────────
echo.
echo  [6/7] Setting up MySQL database...

:: Build mysql auth args
set MYSQL_ARGS=-h%DB_HOST% -P%DB_PORT% -u%DB_USER%
if not "%DB_PASS%"=="" set MYSQL_ARGS=%MYSQL_ARGS% -p%DB_PASS%

:: Create the database if it doesn't exist
echo         Creating database '%DB_NAME%' if needed...
"%MYSQL_EXE%" %MYSQL_ARGS% -e "CREATE DATABASE IF NOT EXISTS \`%DB_NAME%\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>&1
if %errorlevel% neq 0 (
    echo.
    echo  [ERROR] Could not connect to MySQL or create database.
    echo  Make sure XAMPP MySQL is running and credentials are correct.
    pause & exit /b 1
)
echo         Database ready.

:: Run schema.sql
echo         Running schema.sql...
"%MYSQL_EXE%" %MYSQL_ARGS% %DB_NAME% < database\schema.sql 2>&1
if %errorlevel% neq 0 (
    echo  [WARNING] schema.sql returned errors ^(may be safe to ignore if tables already exist^).
)
echo         schema.sql done.

:: Run migration
echo         Running migrate-semester-v2.sql...
"%MYSQL_EXE%" %MYSQL_ARGS% %DB_NAME% < database\migrate-semester-v2.sql 2>&1
if %errorlevel% neq 0 (
    echo  [WARNING] Migration returned errors ^(may be safe if already applied^).
)
echo         Migration done.

echo         Database setup complete  OK

:: ─── Step 7: Seed Data ─────────────────────────────────────────────
echo.
echo  [7/7] Seeding initial data...

echo         Seeding admin account...
call npx ts-node --project tsconfig.json database/seed-admin.ts
if %errorlevel% neq 0 (
    echo  [WARNING] Admin seed returned errors — admin may already exist, which is fine.
)

echo         Seeding departments, courses, subjects...
call npx ts-node --project tsconfig.json database/seed-data.ts
if %errorlevel% neq 0 (
    echo  [WARNING] Data seed returned errors — data may already exist.
)

echo         Seeding faculty accounts...
call npx ts-node --project tsconfig.json database/seed-faculty.ts
if %errorlevel% neq 0 (
    echo  [WARNING] Faculty seed returned errors — faculty may already exist.
)

echo         Seeding student accounts...
call npx ts-node --project tsconfig.json database/seed-students.ts
if %errorlevel% neq 0 (
    echo  [WARNING] Student seed returned errors — students may already exist.
)

echo         Seeding enrollments...
call npx ts-node --project tsconfig.json database/seed-enrollments.ts
if %errorlevel% neq 0 (
    echo  [WARNING] Enrollment seed returned errors — enrollments may already exist.
)

echo.
echo         All seeders complete  OK
echo.

:: ─── Done ────────────────────────────────────────────────────────
echo  ╔══════════════════════════════════════════╗
echo  ║           Setup Complete!                ║
echo  ╚══════════════════════════════════════════╝
echo.
echo   Test credentials:
echo     Admin   : admin@acadtrack.edu / Admin@2026
echo     Faculty : faculty01@acadtrack.edu / Faculty2026
echo     Student : 2026-0001@acadtrack.edu / Student2026
echo.
echo   App URL: %APP_URL%
echo.

set /p START_DEV="  Start the dev server now? (Y/N) [Y]: "
if /i "%START_DEV%"=="" set START_DEV=Y
if /i "%START_DEV%"=="Y" (
    echo.
    echo  Starting dev server...  ^(press Ctrl+C to stop^)
    echo.
    call npm run dev
) else (
    echo.
    echo  Run  npm run dev  when ready.
    echo.
    pause
)

endlocal
